/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package p1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CABECERA = 5;
  /** RegularExpression Id. */
  int HTML = 6;
  /** RegularExpression Id. */
  int HTML_FIN = 7;
  /** RegularExpression Id. */
  int HEAD = 8;
  /** RegularExpression Id. */
  int HEAD_FIN = 9;
  /** RegularExpression Id. */
  int META = 10;
  /** RegularExpression Id. */
  int TITLE = 11;
  /** RegularExpression Id. */
  int BODY = 12;
  /** RegularExpression Id. */
  int BODY_FIN = 13;
  /** RegularExpression Id. */
  int INICIO_TABLA = 14;
  /** RegularExpression Id. */
  int NOMBRE_EMPRESA = 15;
  /** RegularExpression Id. */
  int COTIZACION_EMPRESA = 16;
  /** RegularExpression Id. */
  int A_HREF = 17;
  /** RegularExpression Id. */
  int A_FIN = 18;
  /** RegularExpression Id. */
  int ETIQUETA = 19;
  /** RegularExpression Id. */
  int ETIQUETA_FIN = 20;
  /** RegularExpression Id. */
  int BARRA = 21;
  /** RegularExpression Id. */
  int NUMERO = 22;
  /** RegularExpression Id. */
  int CARACTERES = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<!DOCTYPE html>\"",
    "\"<html>\"",
    "\"</html>\"",
    "\"<head>\"",
    "\"</head>\"",
    "\"<meta\"",
    "\"<title>\"",
    "\"<body\"",
    "\"</body>\"",
    "\"<td class=\\\"bookmark favorites\\\">\"",
    "\"<td class=\\\"name\\\">\"",
    "\"<td class=\\\"price flop\\\">\"",
    "\"<a href=\\\"/cotizacion/\"",
    "\"</a>\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "<NUMERO>",
    "<CARACTERES>",
  };

}
